### ISSUE TITLE
Profile API

### ISSUE THREAD

**Issue by dorianjagusch** [dorianjagusch/ft_transcendence#104]
**Description**:
API for viewing friends more in detail.
Core idea here is that anyone can request the data of others, but depending on their relationship, "stats" and "playHistory" may be set to NULL for all "friendship" values except for "friend". The relationship value is used to determine the content and layout of the profile view

  **Request**: GET "/user/<:user_id>" 
  request body: empty
  
  
**Expected Response**: 
 ```
{
    userObj,
    "friendship": "pending", // | "friend" | "not-friend" | "pending-sent" | "pending-received"
    "placements": [ placementObj, ... ] | null,
    "stats": [ statObj, ... ] | null,
    "playHistory": [ historyObj, ... ] | null,
},  <Response code>
 ```
 The Obj in the response are expected to look like this (for now):
 
  ```
 		userObj: {
			"id": <uri> (of user to be viewed),
			"username": "Username",
			"img": user-img,
			"description": "userdescription"
		};

		statObj: {
                  game: "Pong"
		        highscore: 100,
			gamesPlayed: 10,
			gamesWon: 5,
		};

		placementObj: {
			game: "Pong",
			place: 1,
		};

		historyObj: {
			game: "Pong",
			date: "2021-01-01",
			score: 100,
		};
```	

**Errors**: 
   200: Success
   400: Bad Request: non-numeric value is sent as parameter or more than one is sent
   401: Unauthorised (requesting user is not logged in).
   404: Not Found (requested user-id does not exists).

**Comment by dorianjagusch** [comment]
One major performance issue to consider here, is whether we do the collation of summary stats (i.e. the statObjs from historyObjs) on the FE or BE

**Comment by merituulie** [comment]
looking into this now, I believe we should separate the user from the userstats and create their own routes for getting the stat information!

**Comment by merituulie** [comment]
user route would return the user and the friendship status!
