### ISSUE TITLE
Multiple consequitive games

### ISSUE THREAD

**Issue by dorianjagusch** [dorianjagusch/ft_transcendence#229]
** Description **
Top run multiple consequitive games, either the backend musn't invalidate the token after a game or the frontend creeates a new token 
and saves the guest user's data (-> needs to be encrypted and the passphrase in turn needs to be sent from the backend)

**Comment by sakarisalmi** [comment]
We can definitely set it up so that it is possible to play multiple games consecutively, but this isn't a mandatory requirement for the project, correct? We could definitely get away with forcing the host user to go through the setting up a new match again.

**Comment by dorianjagusch** [comment]
As discussed, we will not allow users to continue playing, but they will have to reauthenticate the other player
